import { Inter } from 'next/font/google';
import './globals.css';
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import Providers from './providers';
import Navbar from './components/navbar/navbar';
import Footer from './components/footer';
import GoToTop from './components/GotoTop';
import { SpeedInsights } from '@vercel/speed-insights/next';
import {Toaster} from "react-hot-toast"
// import { StoreProvider } from '@/redux/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <StoreProvider> */}
        <Providers>
          <Toaster position="top-center" reverseOrder={false} />
          <Navbar />
          {children}
          <SpeedInsights />
          <GoToTop />
          <Footer />
        </Providers>
        {/* </StoreProvider> */}
      </body>
    </html>
  );
}
